# Generated by Django 3.2.2 on 2022-09-04 17:17

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique='True')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('joined', models.DateField(default=datetime.datetime.now)),
                ('img', models.ImageField(upload_to='images/')),
                ('is_agent', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_varified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Booked', 'Booked')], default='Rent', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('building_year', models.DateField()),
                ('img', models.ImageField(upload_to='apartment/')),
                ('about', models.TextField()),
                ('bedroom', models.IntegerField()),
                ('living', models.IntegerField()),
                ('dinning', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('watchman', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('swimmingpool', models.BooleanField(default=False)),
                ('hospital', models.BooleanField(default=False)),
                ('shoppingmall', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateTimeField(default=datetime.datetime.now)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_request_apartment', to='app.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('tour', 'tour'), ('booking', 'booking')], default='Tour', max_length=200)),
                ('message', models.TextField()),
                ('recieve_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_apartment', to='app.apartment')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request_apartment', to='app.apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
