# Generated by Django 3.2.2 on 2022-09-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220901_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='agent',
            new_name='user',
        ),
    ]
