# Generated by Django 3.2.2 on 2022-09-01 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_agent_apartment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='user',
        ),
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
