# Generated by Django 3.2.2 on 2022-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mycustomuser_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
