# Generated by Django 3.2.2 on 2022-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mycustomuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='img',
            field=models.ImageField(upload_to='apartment/'),
        ),
    ]
