# Generated by Django 3.2.2 on 2022-09-01 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_apartment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='user',
            field=models.ManyToManyField(related_name='apartments', to=settings.AUTH_USER_MODEL),
        ),
    ]
