# Generated by Django 3.2.2 on 2022-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_apartment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
