# Generated by Django 3.2.2 on 2022-09-02 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220902_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recieve_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
