# Generated by Django 3.2.2 on 2022-09-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notification_recieve_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='attatched_date',
        ),
    ]
