# Generated by Django 3.2.2 on 2022-09-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_apartment', to='app.apartment'),
        ),
    ]
