# Generated by Django 3.2.2 on 2022-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notification_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('Tour', 'Tour'), ('Booking', 'Booking')], default='Tour', max_length=200),
        ),
    ]
