# Generated by Django 3.2.2 on 2022-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notification_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('tour', 'tour'), ('booking', 'booking')], default='Tour', max_length=200),
        ),
    ]
